Default: &defaults
  database: diplomarbeit-web.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: diplomarbeit-web_test.sqlite3
  <<: *defaults

Staging:
  database: diplomarbeit-web_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: diplomarbeit-web_production.sqlite3
  poolsize: 100
  <<: *defaults
